
export const LOCALE = {
  auth: {
    login: "Log In",
    signup: "Sign Up",
    resetPassword: "Reset Password",
    emailLabel: "Email Address",
    emailPlaceholder: "name@company.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm Password",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember me",
    verificationCodeLabel: "6-Digit Code",
    verificationCodePlaceholder: "123456",
    sendResetCode: "Send Reset Code",
    verifyCode: "Verify Code",
    setNewPassword: "Set New Password",
    successMessage: "Password reset successful!",
    backToLogin: "Back to Login",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "Amina Okonkwo",
    createAccount: "Create Your Account",
    termsNotice: "By continuing, you agree to our Terms and Privacy Policy.",
    resendCode: "Resend Code",
    sending: "Sending...",
    verifying: "Verifying...",
  },
  dashboard: {
    home: "Dashboard Home 👋",
    homeSubtitle: "Explore curated internships and track matches.",
    academy: "CertiAcademy 🎓",
    academySubtitle: "Premium courses with guaranteed internship path.",
    wallet: "Token Wallet 💎",
    walletSubtitle: "Manage your CertiTokens and rewards.",
    referrals: "Refer & Earn 🎁",
    referralsSubtitle: "Get 50 tokens for every referral.",
    feedback: "Feedback 📝",
    feedbackSubtitle: "Help us improve the platform.",
    myApplications: "My Applications 💼",
    assignments: "Assignments 📋",
    settings: "Settings ⚙️",
    logout: "Log Out",
    browseCourses: "Browse Courses",
    earnTokens: "Earn Tokens",
    giveFeedback: "Give Feedback",
    applyNow: "Apply Now",
    applied: "Applied ✓",
    enrolled: "Enrolled ✓",
    enrollWithTokens: "Enroll with Tokens",
    notEnoughTokens: "Not Enough Tokens",
    transactionHistory: "Transaction History",
  },
  recruiter: {
    dashboard: "Recruiter Dashboard",
    dashboardSubtitle: "Verify talent and manage assignments.",
    overview: "Overview",
    postings: "Active Postings",
    postingsSubtitle: "Manage your internship listings.",
    discovery: "Talent Discovery",
    discoverySubtitle: "Search our global pool of verified candidates.",
    tasks: "Task Management",
    ranking: "Leaderboard",
    rankingSubtitle: "Top hiring partners this month.",
    placements: "Placements",
    reviewApps: "Review Apps",
    assignTask: "Assign Task",
    selectHire: "Select & Hire",
    noCandidates: "No candidates match your criteria",
    newInternship: "New Internship",
    postListing: "Post Listing",
  },
  legal: {
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    about: "About Us",
    referral: "Refer a Friend",
  },
  common: {
    done: "Done",
    close: "✕",
    loading: "Loading...",
    error: "An error occurred.",
  }
};
